Imports System
Imports System.Data.Entity.Migrations
Imports Microsoft.VisualBasic

Namespace IdentityMigrations
    Public Partial Class AspNetProfiles2
        Inherits DbMigration
    
        Public Overrides Sub Up()
            AddColumn("dbo.AspNetProfiles", "PWD_Email", Function(c) c.String())
            AddColumn("dbo.AspNetProfiles", "Firma", Function(c) c.String())
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Impianti_Dimensione")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Impianti_Acapo")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Impianti_Troncamento")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Impianti_BarraScorrimentoH")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Impianti_Zebratura")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Impianti_NuovaFinestra")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Amministratori_Dimensione")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Amministratori_Acapo")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Amministratori_Troncamento")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Amministratori_BarraScorrimentoH")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Amministratori_Zebratura")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Amministratori_NuovaFinestra")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Termotecnici_Dimensione")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Termotecnici_Acapo")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Termotecnici_Troncamento")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Termotecnici_BarraScorrimentoH")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Termotecnici_Zebratura")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Termotecnici_NuovaFinestra")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Documenti_Dimensione")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Documenti_Acapo")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Documenti_Troncamento")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Documenti_BarraScorrimentoH")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Documenti_Zebratura")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Documenti_NuovaFinestra")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Utenti_Dimensione")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Utenti_Acapo")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Utenti_Troncamento")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Utenti_BarraScorrimentoH")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Utenti_Zebratura")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Utenti_NuovaFinestra")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Ruoli_Dimensione")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Ruoli_Acapo")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Ruoli_Troncamento")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Ruoli_BarraScorrimentoH")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Ruoli_Zebratura")
            DropColumn("dbo.AspNetProfiles", "Impostazioni_Ruoli_NuovaFinestra")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_Amministrazione")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_Anagrafica")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_CentraleTermica")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_Scadenze")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_Conformita")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_SoloDocumentiAttivi")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxAmministratore")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxTermotecnico")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxProprietario")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxContratto")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxContabilizzazione")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxCentraleTermica")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxScadenze")
            DropColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxVerifiche")
        End Sub
        
        Public Overrides Sub Down()
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxVerifiche", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxScadenze", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxCentraleTermica", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxContabilizzazione", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxContratto", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxProprietario", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxTermotecnico", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_BoxAmministratore", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_SoloDocumentiAttivi", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_Conformita", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_Scadenze", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_CentraleTermica", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_Anagrafica", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Preferenze_Impianti_Amministrazione", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Ruoli_NuovaFinestra", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Ruoli_Zebratura", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Ruoli_BarraScorrimentoH", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Ruoli_Troncamento", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Ruoli_Acapo", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Ruoli_Dimensione", Function(c) c.Int(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Utenti_NuovaFinestra", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Utenti_Zebratura", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Utenti_BarraScorrimentoH", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Utenti_Troncamento", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Utenti_Acapo", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Utenti_Dimensione", Function(c) c.Int(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Documenti_NuovaFinestra", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Documenti_Zebratura", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Documenti_BarraScorrimentoH", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Documenti_Troncamento", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Documenti_Acapo", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Documenti_Dimensione", Function(c) c.Int(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Termotecnici_NuovaFinestra", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Termotecnici_Zebratura", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Termotecnici_BarraScorrimentoH", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Termotecnici_Troncamento", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Termotecnici_Acapo", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Termotecnici_Dimensione", Function(c) c.Int(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Amministratori_NuovaFinestra", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Amministratori_Zebratura", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Amministratori_BarraScorrimentoH", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Amministratori_Troncamento", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Amministratori_Acapo", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Amministratori_Dimensione", Function(c) c.Int(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Impianti_NuovaFinestra", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Impianti_Zebratura", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Impianti_BarraScorrimentoH", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Impianti_Troncamento", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Impianti_Acapo", Function(c) c.Boolean(nullable := False))
            AddColumn("dbo.AspNetProfiles", "Impostazioni_Impianti_Dimensione", Function(c) c.Int(nullable := False))
            DropColumn("dbo.AspNetProfiles", "Firma")
            DropColumn("dbo.AspNetProfiles", "PWD_Email")
        End Sub
    End Class
End Namespace
